#!/usr/bin/env python3
"""Write utils/assets/ur5e.xml: a compact single-arm UR5e + Robotiq 2F-85 MJCF derived from configs/skild_ur5e.urdf.

Only the kinematic chain is needed for FK/IK (no meshes, no inertias). Body origins and joint axes are copied
from the URDF's `right_*` chain (the left chain is identical; the arms differ only in how their bases are
mounted, which utils.arm_models handles). Quaternions are computed here rather than typed by hand.

    python scripts/build_ur5e_mjcf.py            # rewrites utils/assets/ur5e.xml
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from scipy.spatial.transform import Rotation

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "utils" / "assets" / "ur5e.xml"

LIMITS = {
    "shoulder_pan_joint": (-6.28319, 6.28319),
    "shoulder_lift_joint": (-6.28319, 6.28319),
    "elbow_joint": (-3.1415, 3.1415),
    "wrist_1_joint": (-6.28319, 6.28319),
    "wrist_2_joint": (-6.28319, 6.28319),
    "wrist_3_joint": (-6.28319, 6.28319),
}


def quat(rpy) -> str:
    """URDF rpy -> MuJoCo 'w x y z' quaternion string."""
    x, y, z, w = Rotation.from_euler("xyz", rpy).as_quat()
    return " ".join(f"{v:.10g}" if abs(v) > 1e-12 else "0" for v in (w, x, y, z))


def rng(name: str) -> str:
    lo, hi = LIMITS[name]
    return f"{lo:g} {hi:g}"


# (body, pos, rpy, joint, axis) straight from skild_ur5e.urdf (right chain, base frame = right_base)
CHAIN = [
    ("shoulder_link", "0 0 0.163", (0, 0, 0), "shoulder_pan_joint", "0 0 1"),
    ("upper_arm_link", "0 0.138 0", (0, 1.5707963268, 0), "shoulder_lift_joint", "0 1 0"),
    ("forearm_link", "0 -0.131 0.425", (0, 0, 0), "elbow_joint", "0 1 0"),
    ("wrist_1_link", "0 0 0.392", (0, 1.5707963268, 0), "wrist_1_joint", "0 1 0"),
    ("wrist_2_link", "0 0.127 0", (0, 0, 0), "wrist_2_joint", "0 0 1"),
    ("wrist_3_link", "0 0 0.1", (0, 0, 0), "wrist_3_joint", "0 1 0"),
]
# right_robotiq_85_adapter_joint: the UR tool flange, z along the tool
FLANGE_POS, FLANGE_RPY = "0 0.0959 0", (1.5707963268, 0, 3.1415926536)
ADAPTER_M, BASE_TO_TCP_M = 0.016, 0.15        # right_hand_joint, right_tcp_joint
# The pipeline's grasp-site convention is y = jaw axis, z = tool axis. The 2F-85 knuckles sit at +/-x of the
# robotiq base frame, so the site is the tcp frame turned -90 deg about z.
SITE_RPY = (0, 0, -1.5707963268)
# MuJoCo refuses massless moving bodies; the pipeline never simulates dynamics, so any positive value will do.
INERTIAL = '<inertial pos="0 0 0" mass="1" diaginertia="0.01 0.01 0.01"/>'


def build() -> str:
    lines = ['<mujoco model="ur5e_2f85_compact">',
             '  <!-- Generated by scripts/build_ur5e_mjcf.py from configs/skild_ur5e.urdf; do not edit by hand. -->',
             '  <!-- Kinematics only: body origins/joint axes of one UR5e arm in its own base frame, the Robotiq -->',
             '  <!-- 2F-85 flange and the grasp point between its fingertips. No meshes, no inertias. -->',
             '  <compiler angle="radian"/>',
             '  <worldbody>',
             '    <body name="base" pos="0 0 0">']
    indent = "      "
    for body, pos, rpy, joint, axis in CHAIN:
        q = "" if rpy == (0, 0, 0) else f' quat="{quat(rpy)}"'
        lines.append(f'{indent}<body name="{body}" pos="{pos}"{q}>')
        lines.append(f'{indent}  {INERTIAL}')
        lines.append(f'{indent}  <joint name="{joint}" pos="0 0 0" axis="{axis}" range="{rng(joint)}"/>')
        indent += "  "
    lines.append(f'{indent}<body name="flange" pos="{FLANGE_POS}" quat="{quat(FLANGE_RPY)}">')
    lines.append(f'{indent}  {INERTIAL}')
    lines.append(f'{indent}  <site name="tcp_site" pos="0 0 0" quat="{quat(SITE_RPY)}" size="0.005" rgba="1 0 0 1"/>')
    lines.append(f'{indent}  <site name="grasp_site" pos="0 0 {ADAPTER_M + BASE_TO_TCP_M:g}" quat="{quat(SITE_RPY)}" '
                 f'size="0.005" rgba="0 1 0 1"/>')
    lines.append(f'{indent}</body>')
    for _ in CHAIN:
        indent = indent[:-2]
        lines.append(f'{indent}</body>')
    lines += ['    </body>', '  </worldbody>', '</mujoco>', '']
    return "\n".join(lines)


if __name__ == "__main__":
    text = build()
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(text)} bytes)")
    if "--check" in sys.argv:
        import mujoco
        m = mujoco.MjModel.from_xml_path(str(OUT))
        print("bodies:", [mujoco.mj_id2name(m, mujoco.mjtObj.mjOBJ_BODY, i) for i in range(m.nbody)])
        print("joint ranges:", np.round(m.jnt_range, 5).tolist())
